/**
 * Writes dist/_headers after the build, computing a SHA-256 hash for every inline
 * <script> Astro emitted so the Content-Security-Policy can drop 'unsafe-inline'
 * for scripts. Run as part of `pnpm build` (see package.json).
 *
 * style-src keeps 'unsafe-inline': the page sets a handful of CSS custom properties
 * through style attributes (reveal delays, tooltip position), and style attributes
 * cannot be hashed without 'unsafe-hashes', which is weaker than the thing it buys.
 * No script is exempt.
 */
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

const DIST = "dist";
const hashes = new Set();

const walk = (dir) => {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(p);
    else if (entry.name.endsWith(".html")) {
      const html = fs.readFileSync(p, "utf8");
      for (const m of html.matchAll(/<script\b(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g)) {
        const body = m[1];
        if (!body) continue;
        hashes.add(`'sha256-${crypto.createHash("sha256").update(body, "utf8").digest("base64")}'`);
      }
    }
  }
};
walk(DIST);

const scriptSrc = ["'self'", ...hashes, "https://challenges.cloudflare.com"].join(" ");

const csp = [
  "default-src 'self'",
  `script-src ${scriptSrc}`,
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self'",
  "frame-src https://challenges.cloudflare.com",
  "form-action 'self'",
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "object-src 'none'",
  "upgrade-insecure-requests",
].join("; ");

const body = `# Generated by scripts/gen-headers.mjs — do not edit by hand.
# ${hashes.size} inline script hash(es) pinned.

/*
  Content-Security-Policy: ${csp}
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), microphone=(), payment=(), usb=(), interest-cohort=()
  Cross-Origin-Opener-Policy: same-origin
  X-Frame-Options: DENY

/_astro/*
  Cache-Control: public, max-age=31536000, immutable

/fonts/*
  Cache-Control: public, max-age=31536000, immutable

/og/*
  Cache-Control: public, max-age=604800

/api/*
  Cache-Control: no-store
  X-Robots-Tag: noindex

/documents/*
  Cache-Control: private, no-store
  X-Robots-Tag: noindex
`;

fs.writeFileSync(path.join(DIST, "_headers"), body);
console.log(`headers: ${hashes.size} inline script hash(es)`);
